name: 'Install and test'
on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    test:
        strategy:
            matrix:
                node: [20]
        name: Install and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn
            - run: yarn install
            - run: yarn build
            - run: export PRIVATE_KEY=${{secrets.PRIVATE_KEY}}
            - run: yarn test:unit
            - run: yarn test test/integration/rpc.test test/integration/mainnet test/integration/zksync test/integration/utils
