name: 'Install and test'
on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    test:
        strategy:
            matrix:
                node: [18, 20]
        name: Install and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn
            - run: yarn install
            - run: yarn test
